### ISSUE TITLE
Ownership of non-SC provinces

### ISSUE THREAD

**Issue by Wulfheart** [zond/godip#118]
Is it possible to give an nation the ownership of non-SC province?

**Comment by zond** [comment]
This is not supported by godip, mostly since it doesn't have anything to do with adjudication.

If we can find a way to assign non SC ownership to players in a way that makes sense and doesn't provide skewed incentives, I wouldn't be against it since it's an often asked for feature. Do you have a suggestion for this?

I know both @tttppp and @JorenC have ideas about this as well.

**Comment by Wulfheart** [comment]
Oh yes, #67. 
But for example let's take webdiplomacy. If you e.g. look at [this](http://webdiplomacy.net/board.php?gameID=334254#gamePanel) map and click through it you can see that by default there are some provinces which are by default assigned to some nations. 
Taking the approach from #67 would not need any saved state as it is only compiled from the current state. This is only a rendering issue. 
But if you compare this 
![grafik](https://user-images.githubusercontent.com/25671390/100001860-0a06f480-2dc4-11eb-9f76-ad220fbc913c.png)
and this 
![grafik](https://user-images.githubusercontent.com/25671390/100001913-1e4af180-2dc4-11eb-870b-7951b2e6582d.png)
you may also find like me, that the second variant looks nicer in terms of "countries".
However, the webdiplomacy approach would need an persisted state of a province as it is no longer dependent on the current ownership of surrounding SCs. For example https://github.com/diplomacy/diplomacy has also a concept for this.

My proposal: Extending the state struct by an additional property ``influences map[godip.Province]godip.Nation``. There would also need to be an importing function. I could make a draft.

**Comment by zond** [comment]
What I want to avoid is a coloring that is influenced by troop movements, so that beginners feel rewarded for nonsensical moves only made to color non SCs in their colors.

I guess #67 could work, I'd like to see a PR for that.

**Comment by Wulfheart** [comment]
What about the possibility to implement different algorithms for this? This could be a parameter of ``variant.Start()``.

**Comment by zond** [comment]
It could also be implemented in either the server or client, so it's not strictly necessary to even implement it in the adjudication library..

**Comment by zond** [comment]
But yeah, sure, letting it be an optional thing would also work.

**Comment by Wulfheart** [comment]
One question about implementation details: Does setting influence on a supply center also change this SC's ownership or is this action ignored? What do you say?

**Comment by zond** [comment]
I'd say keep influence and ownership separate. Influence is just cosmetics :)

**Comment by Wulfheart** [comment]
In that case influence will ignore SCs as they are always owned and therefore "influenced" by a nation or neutral.

**Comment by zond** [comment]
Sure - each influence implementation will work differently anyway, and each client can choose whether to use it or not.

**Comment by JorenC** [comment]
As the Author of #67 I believe my approach is better than the *influences
map *property.

1) My proposal *does *allow for creating a map like the second proposal -
that's what the XML is for; at the start of the game, it defines which
territories belong to what nation, e.g. *Piedmonte, Bohemia *would belong
to the respective nations, similar to your second picture. This would mean
the map owner would need to make one simple XML file, and if they do not,
the map will follow the default logic (which will not break anything and
still approximately work)
It will also simply work retro-actively, rather than an "influenced-by'
property.

2) By adding rule1 (When an SC get's captured, re-evaluate all adjacent
non-SC territories), this also prevents the default, set-up by XML map to
shift. E.g. Piedmonte would still belong to Italy for the start of the game
*until *either Marseilles or Venice changes owner ('the war approaches').
It would then make sense to re-evalute this.

3) I strongly disagree that Ireland and Iceland should be coloured - they
are neutral and should not be coloured as such.
Indeed, note that they are also marked as impassable in Diplicity. Having
them coloured makes it harder to understand for new players.
[image: image.png]

4) The concept of *influences map* means that a map creator needs to make a
complicated ruleset for new variants - some maps have 80+ territories, and
for *each *territory the maker must make a multitude of *influences
*definitions.
In addition, if multiple SCs border one other territory, it will still come
to "who owns all SCs that influence this territory"*.*

5) A simple ruleset would likely be much easier to implement, as it's the
same as with the influences map, but simpler.

6) The ruleset works in classical but also in all other variants.
There might be an issue with territories only bordering one nation, for
example, if *Tunis* gets taken - by definition, *North Africa* would get
the same colour for the rest of the game, even if Spain is not.
Or, in Vietnam war, the green nation might start with a large border, but
because it's stretched, it might easily get "neutral" territories between
it's SCs.
Considering it's cosmetic, I think this is acceptable.


I would suggest we start with the 67 implementation firstly, and then
possibly extend it with some "influences by" that can override 'SC next to
me', if present. That way we can deliver value in iteration 1, and add
additional value in iteration 2. It also ensures that if there is no
influences property, everything has a fallback.


I forgot to add one rule: "Sea territories can't be coloured". I think this
is self-explanatory.

**Comment by JorenC** [comment]
@Wulfheart maybe join the Discord? https://discord.gg/FttqHc5f that allows us to discuss things more in a chat way, and leave the discussion results for Githb (keep it cleaner). We have a separate Dev channel I can invite you to, if you're commiting..

**Comment by Wulfheart** [comment]
@JorenC yes, I will join the discord for more discussion. 
However to ensure that I understood you correctly: You want to attach some provinces to supply centers. Do I get it correctly?

**Comment by JorenC** [comment]
Hi Alex

Yes and no. The difference between our proposed solutions is that the
provinces are just attached to the neighboring SCs.
In addition, the XML file would create a *starting state*. The rules would
not change or be special.

They wouldn't be attached to an SC, just have a colour at start.
Then, the rules would apply as normal - so the moment one of the SCs
neighboring that province (let's say *Piedmonte *starts green. For three
turns, nothing changes - *Marseilles* is blue, *Venice *is green. On turn
four, *Venice *becomes red. Now, Piedmonte is a neighboring province and
gets evaluated - one blue (marseilles), one red (venice), means it would
turn neutral - it's a contested zone between two major powers...

So, I don't want to attach provinces to supply centers - I want to make one
standard, simple rule set that applies to all countries.
By making it only execute when neighboring SCs change, a simple solution
like a starting state (which would just be *pie - green, gascony - blue* etc
for any neutral SCs you want coloured) would have impact as long as needed,
until the actual situation changes.

With regards,

Joren

**Comment by Wulfheart** [comment]
@JorenC I made a custom package for this because I felt like it doesn't belong into the core. 
https://github.com/Wulfheart/godip-influence allows the definition of custom "influence" functions.

**Comment by zond** [comment]
Pretty cool!

@Wulfheart is it ok if we mentioned this in the godip README?

@tttppp do you want to implement your idea using this concept?

**Comment by Wulfheart** [comment]
> @Wulfheart is it ok if we mentioned this in the godip README?

Of course. I have already provided a license for the project.

**Comment by JorenC** [comment]
Super awesome!
If this would make it a step closer, super nice!

**Comment by tttppp** [comment]
I think my only contributions on this topic were:
1. I probably wouldn't use it.
2. If it was enabled then I'd want a different colour for influenced provinces and owned SCs.
3. For consistency I think the sea provinces should be eligible for colouring in a similar way to the land provinces.

Having said this, I think it's a great piece of work, since this is probably the most requested feature.

**Comment by Wulfheart** [comment]
You can use your own algorithm. It is just a wrapper with some predefined algorithms.

**Comment by zond** [comment]
I'll close this now. Added mention of your project in the README :)
